INSERT INTO `zone` (`zone_id`, `zone_name`) VALUES
(1, 'Mechi'),
(2, 'Rapti'),
(3, 'Bagmati'),
(4, 'Karnali'),
(5, 'Sagarmatha'),
(6, 'Koshi'),
(7, 'Narayani'),
(8, 'Mahakali'),
(9, 'Gandaki'),
(10, 'Janakpur'),
(11, 'Lumbini'),
(12, 'Seti'),
(13, 'Bheri'),
(14, 'Dhawalagiri');